version: '3.8'
services:
    lovd:        
        build:
          context: ./
          dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql:5.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        
        ports:
            - "9906:3306"
        env_file:
            - .env
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - '8080:80'
      restart: always
      environment:
        PMA_HOST: db
      depends_on:
        - db
networks:
  default:
    external:
      name: lovdplus