<?php
// Leiden specific adapter settings.
$_INSTANCE_CONFIG['attachments'] = false;
$_INSTANCE_CONFIG['conversion']['suffixes']['vep'] = 'directvep.data.lovd';
$_INSTANCE_CONFIG['conversion']['create_meta_file_if_missing'] = false;
$_INSTANCE_CONFIG['conversion']['enforce_hgnc_gene'] = false;
$_INSTANCE_CONFIG['conversion']['verbosity_other'] = 9;

$_INSTANCE_CONFIG['viewlists'] = array(
    // If set to true, ViewLists are not allowed to be downloaded, except specifically
    //  enabled as 'allow_download_from_level' in the ViewLists's settings below.
    'restrict_downloads' => true,

    // The screenings data listing on the individual's detailed view.
    'Screenings_for_I_VE' => array(
        'cols_to_show' => array(
            // Select these columns for the screenings listing on the individual's page.
            // Note, that you also need to define the hidden columns that
            //  are to be active, since LOVD+ might be filtering on them.
            // You can change the order of columns to any order you like.
            'id',
            'individualid', // Hidden, but needed for search.
            'Screening/Panel_coverage/Fraction',
            'Screening/Father/Panel_coverage/Fraction',
            'Screening/Mother/Panel_coverage/Fraction',
            'curation_progress_',
            'variants_found_',
            'created_date_',
            'analysis_status',
        )
    ),
    // The data analysis results data listing.
    'CustomVL_AnalysisRunResults_for_I_VE' => array(
        // Even when downloading ViewLists is restricted, allow downloading from LEVEL_MANAGER.
        'allow_download_from_level' => LEVEL_MANAGER,
        'cols_to_show' => array(
            // Select these columns for the analysis results table.
            // Note, that you also need to define the hidden columns that
            //  are to be active, since LOVD+ might be filtering on them.
            // By default, these columns are sorted by object type, but you can change the order to any order you like.
            'curation_status_',
            'curation_statusid',
            'variantid',
            'vog_effect',
            'chromosome',
            'allele_',
            'VariantOnGenome/DNA',
            'VariantOnGenome/Alamut',
            'VariantOnGenome/Conservation_score/PhyloP',
            'VariantOnGenome/HGMD/Association',
            'VariantOnGenome/Sequencing/Quality',
            'obs_variant',
            'obs_var_ind_ratio',
            'obs_disease',
            'obs_var_dis_ind_ratio',

            'VariantOnGenome/Sequencing/Depth/Alt/Fraction',
            'VariantOnGenome/Sequencing/Father/Depth/Alt/Fraction',
            'VariantOnGenome/Sequencing/Mother/Depth/Alt/Fraction',

            'gene_disease_names',
            'VariantOnTranscript/DNA',
            'VariantOnTranscript/Protein',
            'VariantOnTranscript/GVS/Function',
            'gene_OMIM_',

            'runid',

            'gene_panels',
        )
    )
);

$_INSTANCE_CONFIG['observation_counts'] = array(
    'genepanel' => array(
        'columns' => array(
            'value' => 'Gene Panel',
            'total_individuals' => 'Total # Individuals',
            'percentage' => 'Percentage (%)'
        ),
        'categories' => array(
            'all',
            'gender',
        ),
        'show_decimals' => 1,
    ),
    'general' => array(
        // if columns is empty, use default columns list
        'columns' => array(
            'label' => 'Category',
            'value' => 'Value',
            'percentage' => 'Percentage (%)'
        ),
        'categories' => array(
            'all',
            'Individual/Gender',
        ),
        'show_decimals' => 1,
        'min_population_size' => 100,
    ),
);





class LOVD_LeidenDataConverter extends LOVD_DefaultDataConverter {
    // Contains the overloaded functions that we want different from the default.

    function cleanHeaders ($aHeaders)
    {
        // Leiden's headers can be appended by the Miracle ID.
        // Clean this off, and verify the identity of this file.
        // Check the child's Miracle ID with that we have in the meta data file, and die if there is a mismatch.
        foreach ($aHeaders as $key => $sHeader) {
            if (preg_match('/(Child|Patient|Father|Mother)_(\d+)$/', $sHeader, $aRegs)) {
                // If Child, check ID.
                if (!empty($this->aScriptVars['nMiracleID']) && in_array($aRegs[1], array('Child', 'Patient')) && $aRegs[2] != $this->aScriptVars['nMiracleID']) {
                    // Here, we won't try and remove the temp file. We need it for diagnostics, and it will save us from running into the same error over and over again.
                    die('Fatal: Miracle ID of ' . $aRegs[1] . ' (' . $aRegs[2] . ') does not match that from the meta file (' . $this->aScriptVars['nMiracleID'] . ')' . "\n");
                }
                // Clean ID from column.
                $aHeaders[$key] = substr($sHeader, 0, -(strlen($aRegs[2]) + 1));
                // Also clean "Child" and "Patient" off.
                $aHeaders[$key] = preg_replace('/_(Child|Patient)$/', '', $aHeaders[$key]);
            }
        }

        return $aHeaders;
    }





    function getInputFilePrefixPattern ()
    {
        // Returns the regex pattern of the prefix of variant input file names.
        // The prefix is often the sample ID or individual ID, and can be formatted to your liking.
        // Data files must be named "prefix.suffix", using the suffixes as defined in the conversion script.

        // If using sub patterns, make sure they are not counted, like so:
        //  (?:subpattern)
        return '(?:Child|Patient)_(?:\d+)';
    }





    function getRequiredHeaderColumns ()
    {
        // Returns an array of required variant input file column headers.
        // The order of these columns does NOT matter.

        return array(
            'chromosome',
            'position',
            'REF',
            'ALT',
            'QUAL',
            'FILTERvcf',
            'GT',
            'SYMBOL',
            'Feature',
        );
    }





    function prepareGeneAliases ()
    {
        // Return an array of gene aliases, with the gene symbol as given by VEP
        //  as the key, and the symbol as known by LOVD/HGNC as the value.
        // Example:
        // return array(
        //     'C4orf40' => 'PRR27',
        // );

        // To build this list:
        // tail -n 100000 /var/mail/ifokkema | grep "is given to us as" | sort | uniq \
        //   | sed 's/^Gene stored as //' | sed 's/ is given to us as /\t/' | cut -d ';' -f 1 \
        //   | awk '{print $2 " => " $1 ","}'

        return array(
            // This list needs to be replaced now and then.
            // Added 2018-08-14, expire 2019-08-14.
            'C10orf137' => 'EDRF1',
            'C11orf93' => 'COLCA2',
            'C12orf52' => 'RITA1',
            'C13orf45' => 'LMO7DN',
            'C1orf63' => 'RSRP1',
            'C20orf201' => 'LKAAEAR1',
            'C3orf37' => 'HMCES',
            'C3orf43' => 'SMCO1',
            'C6orf229' => 'ARMH2',
            'C6orf70' => 'ERMARD',
            'C7orf41' => 'MTURN',
            'C9orf123' => 'DMAC1',
            'CXorf48' => 'CT55',
            'CXorf61' => 'CT83',
            'CXXC11' => 'RTP5',
            'KIAA1704' => 'GPALPP1',
            'PHF15' => 'JADE2',
            'PHF16' => 'JADE3',
            'PLAC1L' => 'OOSP2',
            'PNMA6C' => 'PNMA6A',
            'PRAC' => 'PRAC1',
            'RPS17L' => 'RPS17',
            'SCXB' => 'SCX',
            'SELRC1' => 'COA7',
            'SGK196' => 'POMK',
            'SMCR7' => 'MIEF2',
            'SPANXB2' => 'SPANXB1',
            'SPATA31A2' => 'SPATA31A1',
            'UQCC' => 'UQCC1',

            // 2018-09-11; Expire 2019-09-11.
            'AATK-AS1' => 'PVALEF',
            'ADC' => 'AZIN2',
            'AIM1L' => 'CRYBG2',
            'APITD1' => 'CENPS',
            'APITD1-CORT' => 'CENPS-CORT',
            'ATPIF1' => 'ATP5IF1',
            'BAI2' => 'ADGRB2',
            'BAIAP2-AS1' => 'BAIAP2-DT',
            'C15orf59-AS1' => 'INSYN1-AS1',
            'C16orf98' => 'PYCARD-AS1',
            'C19orf52' => 'TIMM29',
            'C19orf82' => 'ZNF561-AS1',
            'C1orf170' => 'PERM1',
            'C1orf86' => 'FAAP20',
            'C20orf166-AS1' => 'MIR1-1HG-AS1',
            'CCDC163P' => 'CCDC163',
            'CCDC23' => 'SVBP',
            'CCDC74B-AS1' => 'MED15P9',
            'CPSF3L' => 'INTS11',
            'CRAT40' => 'LINC02563',
            'DIGIT' => 'GSC-DT',
            'DKFZP434L187' => 'LINC02249',
            'DLX2-AS1' => 'DLX2-DT',
            'EFTUD1P1' => 'EFL1P1',
            'EIF3J-AS1' => 'EIF3J-DT',
            'FAM132A' => 'C1QTNF12',
            'FAM213B' => 'PRXL2B',
            'FAM27L' => 'FAM27E5',
            'FAM46B' => 'TENT5B',
            'FLJ10038' => 'GABPB1-IT1',
            'FLJ26245' => 'LINC02167',
            'FLJ30403' => 'LINC01530',
            'GLTPD1' => 'CPTP',
            'GLTSCR2-AS1' => 'NOP53-AS1',
            'GOLGA6L5' => 'GOLGA6L5P',
            'HDGFRP2' => 'HDGFL2',
            'HNRNPCP5' => 'HNRNPCL2',
            'HOXD-AS1' => 'HAGLR',
            'KIAA0125' => 'FAM30A',
            'KIAA1751' => 'CFAP74',
            'LEPRE1' => 'P3H1',
            'LINC00116' => 'MTLN',
            'LINC00338' => 'SNHG20',
            'LINC00657' => 'NORAD',
            'LINC00675' => 'TMEM238L',
            'LINC01158' => 'PANTR1',
            'LINC01314' => 'CTXND1',
            'LINC01384' => 'LNCNEF',
            'LINC02081' => 'SCAT1',
            'LPPR2' => 'PLPPR2',
            'LPPR3' => 'PLPPR3',
            'MAGOH2' => 'MAGOH2P',
            'MGC45922' => 'LINC01869',
            'MGC57346' => 'ARF2P',
            'MIR203' => 'MIR203A',
            'MIR3545' => 'MIR203B',
            'MIR4433' => 'MIR4433A',
            'MIR549' => 'MIR549A',
            'MMP24-AS1' => 'MMP24OS',
            'PAPL' => 'ACP7',
            'PPY2' => 'PPY2P',
            'PRAMEF23' => 'PRAMEF5',
            'PRCAT47' => 'ARLNC1',
            'PTCHD2' => 'DISP3',
            'RNASEK-C17ORF49' => 'RNASEK-C17orf49',
            'RSG1' => 'CPLANE2',
            'SELV' => 'SELENOV',
            'SEPN1' => 'SELENON',
            'SLC35E2' => 'SLC35E2A',
            'SNORA39' => 'SNORA71E',
            'SNORD85' => 'SNORD103C',
            'TCONS_00024492' => 'LINC01082',
            'TISP43' => 'PRSS40A',
            'TMEM57' => 'MACO1',
            'TRAPPC2P1' => 'TRAPPC2B',
            'TRNAA3' => 'TRA-AGC8-1',
            'TRNAA4' => 'TRA-CGC3-1',
            'TRNAC12' => 'TRC-GCA5-1',
            'TRNAC24' => 'TRC-GCA8-1',
            'TRNAC29' => 'TRC-GCA2-4',
            'TRNAC30' => 'TRC-GCA14-1',
            'TRNAC9' => 'TRC-GCA2-3',
            'TRNAD17' => 'TRD-GTC2-11',
            'TRNAE11' => 'TRE-TTC2-2',
            'TRNAE1' => 'TRE-TTC3-1',
            'TRNAE26' => 'TRE-TTC1-1',
            'TRNAF10' => 'TRF-GAA1-6',
            'TRNAG16' => 'TRG-GCC2-5',
            'TRNAG18' => 'TRG-TCC3-1',
            'TRNAG19' => 'TRG-GCC2-2',
            'TRNAG20' => 'TRG-GCC5-1',
            'TRNAG22' => 'TRG-CCC2-1',
            'TRNAG2' => 'TRG-GCC2-6',
            'TRNAG3' => 'TRG-TCC1-1',
            'TRNAG4' => 'TRG-CCC2-2',
            'TRNAG5' => 'TRG-GCC3-1',
            'TRNAG6' => 'TRG-GCC2-4',
            'TRNAH1' => 'TRH-GTG1-7',
            'TRNAH2' => 'TRH-GTG1-8',
            'TRNAH6' => 'TRH-GTG1-9',
            'TRNAI13' => 'TRI-TAT2-1',
            'TRNAI15' => 'TRI-AAT5-4',
            'TRNAI18' => 'TRI-TAT1-1',
            'TRNAI23' => 'TRI-AAT5-5',
            'TRNAI24' => 'TRI-AAT4-1',
            'TRNAK13' => 'TRK-CTT1-1',
            'TRNAK15' => 'TRK-CTT3-1',
            'TRNAK17' => 'TRK-TTT1-1',
            'TRNAK1' => 'TRK-TTT3-5',
            'TRNAK21' => 'TRK-CTT5-1',
            'TRNAK26' => 'TRK-CTT2-5',
            'TRNAK4' => 'TRK-CTT6-1',
            'TRNAK6' => 'TRK-CTT1-2',
            'TRNAK9' => 'TRK-CTT4-1',
            'TRNAL11' => 'TRL-CAG2-2',
            'TRNAL13' => 'TRL-CAG2-1',
            'TRNAL2' => 'TRL-TAG1-1',
            'TRNAL7' => 'TRL-TAG3-1',
            'TRNAM13' => 'TRM-CAT6-1',
            'TRNAM14' => 'TRX-CAT1-8',
            'TRNAM9' => 'TRM-CAT2-1',
            'TRNAN17' => 'TRN-GTT2-5',
            'TRNAN20' => 'TRN-GTT2-6',
            'TRNAP12' => 'TRP-CGG1-2',
            'TRNAP19' => 'TRP-TGG3-3',
            'TRNAP21' => 'TRP-TGG3-4',
            'TRNAP5' => 'TRP-AGG1-1',
            'TRNAP8' => 'TRP-CGG1-3',
            'TRNAP9' => 'TRP-AGG2-7',
            'TRNAQ1' => 'TRQ-CTG1-5',
            'TRNAQ24' => 'TRQ-CTG1-4',
            'TRNAQ2' => 'TRQ-TTG1-1',
            'TRNAR18' => 'TRR-CCT3-1',
            'TRNAR19' => 'TRR-CCG1-3',
            'TRNAR1' => 'TRR-TCT2-1',
            'TRNAR20' => 'TRR-CCT2-1',
            'TRNAR21' => 'TRR-ACG1-3',
            'TRNAR22' => 'TRR-TCG1-1',
            'TRNAR23' => 'TRR-CCT5-1',
            'TRNAR25' => 'TRR-TCG3-1',
            'TRNAR4' => 'TRR-CCG2-1',
            'TRNAR8' => 'TRR-CCT1-1',
            'TRNAS14' => 'TRS-AGA2-6',
            'TRNAS18' => 'TRS-GCT4-2',
            'TRNAS23' => 'TRS-GCT4-3',
            'TRNAS6' => 'TRS-CGA1-1',
            'TRNAT10' => 'TRT-CGT4-1',
            'TRNAT22' => 'TRT-AGT5-1',
            'TRNAT4' => 'TRT-AGT1-3',
            'TRNAT6' => 'TRT-CGT2-1',
            'TRNAT8' => 'TRT-AGT1-1',
            'TRNAT9' => 'TRT-AGT1-2',
            'TRNAU1' => 'TRU-TCA1-1',
            'TRNAV32' => 'TRV-CAC3-1',
            'TRNAW3' => 'TRW-CCA3-3',
            'TRNAW4' => 'TRW-CCA1-1',
            'TRNAW7' => 'TRW-CCA2-1',
            'TRNAY4' => 'TRY-GTA2-1',
            'TRNAY9' => 'TRY-ATA1-1',
            'UTP11L' => 'UTP11',
            'WTH3DI' => 'RAB6D',
            'ZAK' => 'MAP3K20',
            'ZNF542' => 'ZNF542P',

            // 2023-01-27; New additions after starting to use Dragen.
            'SDHAF3' => 'ACN9',
            'ACP4' => 'ACPT',
            'GCNA' => 'ACRC',
            'ACTN1-AS1' => 'ACTN1-DT',
            'COQ8A' => 'ADCK3',
            'COQ8B' => 'ADCK4',
            'GRK2' => 'ADRBK1',
            'GRK3' => 'ADRBK2',
            'GPAT4' => 'AGPAT6',
            'GPAT3' => 'AGPAT9',
            'AHSA2P' => 'AHSA2',
            'CRYBG1' => 'AIM1',
            'CRYBG2' => 'AIM1L',
            'ALMS1P1' => 'ALMS1P',
            'C2CD6' => 'ALS2CR11',
            'JAML' => 'AMICA1',
            'SLF1' => 'ANKRD32',
            'APCDD1L-AS1' => 'APCDD1L-DT',
            'CENPS-CORT' => 'APITD1-CORT',
            'CENPS' => 'APITD1',
            'NAXE' => 'APOA1BP',
            'C9orf37' => 'ARRDC1-AS1',
            'INTS13' => 'ASUN',
            'ATE1-AS1' => 'ATE1OSP',
            'PGGHG' => 'ATHL1',
            'ATP1A1-AS1' => 'ATP1A1OS',
            'ATP5F1A' => 'ATP5A1',
            'ATP5F1B' => 'ATP5B',
            'ATP5F1C' => 'ATP5C1',
            'ATP5F1D' => 'ATP5D',
            'ATP5F1E' => 'ATP5E',
            'ATP5F1EP2' => 'ATP5EP2',
            'ATP5PB' => 'ATP5F1',
            'ATP5MC1' => 'ATP5G1',
            'ATP5MC2' => 'ATP5G2',
            'ATP5MC3' => 'ATP5G3',
            'ATP5PD' => 'ATP5H',
            'ATP5ME' => 'ATP5I',
            'ATP5MF' => 'ATP5J2',
            'ATP5MF-PTCD1' => 'ATP5J2-PTCD1',
            'ATP5PF' => 'ATP5J',
            'ATP5MGL' => 'ATP5L2',
            'ATP5MG' => 'ATP5L',
            'ATP5PO' => 'ATP5O',
            'DMAC2' => 'ATP5SL',
            'ATP5IF1' => 'ATPIF1',
            'AURKAPS1' => 'AURKAP1',
            'B3GLCT' => 'B3GALTL',
            'B4GAT1' => 'B3GNT1',
            'BRE-AS1' => 'BABAM2-AS1',
            'ADGRB1' => 'BAI1',
            'ADGRB3' => 'BAI3',
            'BARX1-AS1' => 'BARX1-DT',
            'BCO1' => 'BCMO1',
            'ABHD11-AS1' => 'BICDL3P',
            'ARNTL2-AS1' => 'BMAL2-AS1',
            'BMS1P5' => 'BMS1P1',
            'BOLA3-AS1' => 'BOLA3-DT',
            'BABAM2' => 'BRE',
            'BRWD1-IT2' => 'BRWD1-AS2',
            'LINC01136' => 'BTG2-DT',
            'TSPOAP1' => 'BZRAP1',
            'CABCOCO1' => 'C10orf107',
            'DEPP1' => 'C10orf10',
            'LRMDA' => 'C10orf11',
            'TMEM273' => 'C10orf128',
            'ACSM6' => 'C10orf129',
            'TWNK' => 'C10orf2',
            'BORCS7' => 'C10orf32',
            'FAM241B' => 'C10orf35',
            'VSIR' => 'C10orf54',
            'ARMH3' => 'C10orf76',
            'RPARP-AS1' => 'C10orf95-AS1',
            'LMNTD2' => 'C11orf35',
            'NTM-AS1' => 'C11orf39',
            'LBHD1' => 'C11orf48',
            'NKAPD1' => 'C11orf57',
            'JHY' => 'C11orf63',
            'CFAP300' => 'C11orf70',
            'HIKESHI' => 'C11orf73',
            'DDIAS' => 'C11orf82',
            'UQCC3' => 'C11orf83',
            'SPINDOC' => 'C11orf84',
            'ATG101' => 'C12orf44',
            'CFAP54' => 'C12orf55',
            'TIGAR' => 'C12orf5',
            'LINC01619' => 'C12orf79',
            'CCDC198' => 'C14orf105',
            'GON7' => 'C14orf142',
            'DGLUCY' => 'C14orf159',
            'RNF212B' => 'C14orf164',
            'LRRC74A' => 'C14orf166B',
            'RTRAF' => 'C14orf166',
            'ERG28' => 'C14orf1',
            'LINC01551' => 'C14orf23',
            'ATP5MPL' => 'C14orf2',
            'ARMH4' => 'C14orf37',
            'CLBA1' => 'C14orf79',
            'TEDC1' => 'C14orf80',
            'CFAP161' => 'C15orf26',
            'TMEM266' => 'C15orf27',
            'TERB2' => 'C15orf43',
            'CCDC9B' => 'C15orf52',
            'CCDC32' => 'C15orf57',
            'REC114' => 'C15orf60',
            'PRR35' => 'C16orf11',
            'GAS8-AS1' => 'C16orf3',
            'MOSMO' => 'C16orf52',
            'TEDC2' => 'C16orf59',
            'VPS35L' => 'C16orf62',
            'CCDC189' => 'C16orf93',
            'NATD1' => 'C17orf103',
            'MEIOC' => 'C17orf104',
            'CFAP97D1' => 'C17orf105',
            'BORCS6' => 'C17orf59',
            'CYBC1' => 'C17orf62',
            'FAAP100' => 'C17orf70',
            'PRR29' => 'C17orf72',
            'SPEM2' => 'C17orf74',
            'NCBP3' => 'C17orf85',
            'NDUFAF8' => 'C17orf89',
            'EPOP' => 'C17orf96',
            'TYMSOS' => 'C18orf56',
            'RMC1' => 'C18orf8',
            'MYDGF' => 'C19orf10',
            'CBARP' => 'C19orf26',
            'PEAK3' => 'C19orf35',
            'TRIR' => 'C19orf43',
            'TEX45' => 'C19orf45',
            'TIMM29' => 'C19orf52',
            'PROSER3' => 'C19orf55',
            'MCEMP1' => 'C19orf59',
            'REX1BD' => 'C19orf60',
            'ZSWIM9' => 'C19orf68',
            'SMIM24' => 'C19orf77',
            'ANGPTL8' => 'C19orf80',
            'CATSPERE' => 'C1orf101',
            'INAVA' => 'C1orf106',
            'CCDC190' => 'C1orf110',
            'SPATA46' => 'C1orf111',
            'FYB2' => 'C1orf168',
            'KDF1' => 'C1orf172',
            'ERICH3' => 'C1orf173',
            'LEXM' => 'C1orf177',
            'RHEX' => 'C1orf186',
            'CFAP126' => 'C1orf192',
            'SNHG28' => 'C1orf204',
            'SPATA45' => 'C1orf227',
            'ARMH1' => 'C1orf228',
            'FNDC10' => 'C1orf233',
            'TEX46' => 'C1orf234',
            'ODR4' => 'C1orf27',
            'SRARP' => 'C1orf64',
            'CCDC185' => 'C1orf65',
            'GLMP' => 'C1orf85',
            'FAAP20' => 'C1orf86',
            'STUM' => 'C1orf95',
            'PCOTH' => 'C1QTNF9B-AS1',
            'NOL4L' => 'C20orf112',
            'MIR1-1HG' => 'C20orf166',
            'RAB5IF' => 'C20orf24',
            'CFAP61' => 'C20orf26',
            'LINC01620' => 'C20orf62',
            'C21orf62-AS1' => 'C21orf49',
            'CFAP298' => 'C21orf59',
            'LINC01547' => 'C21orf67',
            'TSPEAR-AS2' => 'C21orf90',
            'PRR34' => 'C22orf26',
            'RTL10' => 'C22orf29',
            'DRICH1' => 'C22orf43',
            'WDCP' => 'C2orf44',
            'MAIP1' => 'C2orf47',
            'PRR30' => 'C2orf53',
            'TEX44' => 'C2orf57',
            'STPG4' => 'C2orf61',
            'SNORC' => 'C2orf82',
            'NEPRO' => 'C3orf17',
            'PQLC2L' => 'C3orf55',
            'FOXL2NB' => 'C3orf72',
            'LINC00694' => 'C3orf86P',
            'ZGRF1' => 'C4orf21',
            'CFAP299' => 'C4orf22',
            'ODAPH' => 'C4orf26',
            'HPF1' => 'C4orf27',
            'ABHD18' => 'C4orf29',
            'FAM241A' => 'C4orf32',
            'DCANP1' => 'C5orf20',
            'TMEM267' => 'C5orf28',
            'MRNIP' => 'C5orf45',
            'TEX43' => 'C5orf48',
            'EXOC3-AS1' => 'C5orf55',
            'CFAP206' => 'C6orf165',
            'SMIM29' => 'C6orf1',
            'MPIG6B' => 'C6orf25',
            'SDHAF4' => 'C6orf57',
            'SUGCT' => 'C7orf10',
            'LLCFC1' => 'C7orf34',
            'CYREN' => 'C7orf49',
            'BMT2' => 'C7orf60',
            'TEX47' => 'C7orf62',
            'CFAP69' => 'C7orf63',
            'SPATA48' => 'C7orf72',
            'STMP1' => 'C7orf73',
            'PPDPFL' => 'C8orf22',
            'TCIM' => 'C8orf4',
            'SPOUT1' => 'C9orf114',
            'CFAP157' => 'C9orf117',
            'PAXX' => 'C9orf142',
            'AJM1' => 'C9orf172',
            'STPG3' => 'C9orf173',
            'CDKN2A-AS1' => 'C9orf53',
            'TMEM250' => 'C9orf69',
            'STKLD1' => 'C9orf96',
            'SPACA9' => 'C9orf9',
            'CAPN10-AS1' => 'CAPN10-DT',
            'NAXD' => 'CARKD',
            'C9orf41-AS1' => 'CARNMT1-AS1',
            'KNL1' => 'CASC5',
            'CASP16P' => 'CASP16',
            'KYAT3' => 'CCBL2',
            'SGF29' => 'CCDC101',
            'CFAP65' => 'CCDC108',
            'MCUB' => 'CCDC109B',
            'VPS50' => 'CCDC132',
            'DRC7' => 'CCDC135',
            'CCDC144B' => 'CCDC144BP',
            'CFAP58' => 'CCDC147',
            'BBOF1' => 'CCDC176',
            'CFAP45' => 'CCDC19',
            'SVBP' => 'CCDC23',
            'GVQW2' => 'CCDC28A-AS1',
            'CFAP100' => 'CCDC37',
            'CFAP73' => 'CCDC42B',
            'BICDL2' => 'CCDC64B',
            'BICDL1' => 'CCDC64',
            'DEUP1' => 'CCDC67',
            'TERB1' => 'CCDC79',
            'LINC01279' => 'CCDC80',
            'YJU2' => 'CCDC94',
            'NOCT' => 'CCRN4L',
            'ADGRE5' => 'CD97',
            'CDC37L1-AS1' => 'CDC37L1-DT',
            'CDIPT-AS1' => 'CDIPTOSP',
            'CEBPA-AS1' => 'CEBPA-DT',
            'ADA2' => 'CECR1',
            'HDHD5' => 'CECR5',
            'TMEM121B' => 'CECR6',
            'CENPBD1P1' => 'CENPBD2P',
            'CCDC37-AS1' => 'CFAP100-DT',
            'CFAP58-AS1' => 'CFAP58-DT',
            'C9orf135-AS1' => 'CFAP95-DT',
            'CGB3' => 'CGB',
            'LINC01578' => 'CHASERR',
            'CHKB-AS1' => 'CHKB-DT',
            'LINC00535' => 'CIBAR1-DT',
            'CIDECP' => 'CIDECP1',
            'UTP4' => 'CIRH1A',
            'LINC01835' => 'CLEC4OP',
            'ZCCHC23' => 'COL25A1-DT',
            'LINC01510' => 'COMETT',
            'CPEB2-AS1' => 'CPEB2-DT',
            'INTS11' => 'CPSF3L',
            'CRAMP1' => 'CRAMP1L',
            'KAT14' => 'CSRP2BP',
            'CTBP1-AS2' => 'CTBP1-DT',
            'IL8' => 'CXCL8',
            'BCLAF3' => 'CXorf23',
            'HYPM' => 'CXorf27',
            'PRR32' => 'CXorf64',
            'PRORY' => 'CYorf17',
            'TKFC' => 'DAK',
            'ACKR1' => 'DARC',
            'DARS-AS1' => 'DARS1-AS1',
            'INTS6L' => 'DDX26B',
            'DEFB131A' => 'DEFB131',
            'GSDME' => 'DFNA5',
            'WHRN' => 'DFNB31',
            'PJVK' => 'DFNB59',
            'ESS2' => 'DGCR14',
            'DHFR2' => 'DHFRL1',
            'PRR26' => 'DIP2C-AS1',
            'ERICH1-AS1' => 'DLGAP2',
            'DNAJB5-AS1' => 'DNAJB5-DT',
            'DNAJC3-AS1' => 'DNAJC3-DT',
            'VPS26C' => 'DSCR3',
            'LINC01296' => 'DUXAP9',
            'DNAAF4' => 'DYX1C1',
            'CRACR2A' => 'EFCAB4B',
            'EFL1' => 'EFTUD1',
            'EHMT1-IT1' => 'EHMT1',
            'ADGRL4' => 'ELTD1',
            'ADGRE1' => 'EMR1',
            'ADGRE2' => 'EMR2',
            'TEPSIN' => 'ENTHD2',
            'LINC00894' => 'EOLA2-DT',
            'EPB41L4A-AS2' => 'EPB41L4A-DT',
            'ERBIN' => 'ERBB2IP',
            'ERO1B' => 'ERO1LB',
            'FCMR' => 'FAIM3',
            'RFLNA' => 'FAM101A',
            'RFLNB' => 'FAM101B',
            'PHETA2' => 'FAM109B',
            'TCAF1' => 'FAM115A',
            'TCAF2' => 'FAM115C',
            'RTL8C' => 'FAM127A',
            'RTL8B' => 'FAM127C',
            'C1QTNF12' => 'FAM132A',
            'ERFE' => 'FAM132B',
            'RETREG2' => 'FAM134A',
            'RETREG1' => 'FAM134B',
            'RETREG3' => 'FAM134C',
            'ALKAL1' => 'FAM150A',
            'ALKAL2' => 'FAM150B',
            'FAM153C' => 'FAM153CP',
            'SAXO2' => 'FAM154B',
            'SHISAL2A' => 'FAM159A',
            'SHISAL2B' => 'FAM159B',
            'ABRAXAS1' => 'FAM175A',
            'ABRAXAS2' => 'FAM175B',
            'SLF2' => 'FAM178A',
            'TOGARAM2' => 'FAM179A',
            'TOGARAM1' => 'FAM179B',
            'MINDY3' => 'FAM188A',
            'MINDY4' => 'FAM188B',
            'ERICH6B' => 'FAM194B',
            'FAM197Y7P' => 'FAM197Y7',
            'FAM205BP' => 'FAM205B',
            'LRRC75A' => 'FAM211A',
            'LRRC75B' => 'FAM211B',
            'WASHC2C' => 'FAM21C',
            'LINC01663' => 'FAM230F',
            'LINC01658' => 'FAM230I',
            'CALHM4' => 'FAM26D',
            'CALHM5' => 'FAM26E',
            'CALHM6' => 'FAM26F',
            'CCNQ' => 'FAM58A',
            'SINHCAF' => 'FAM60A',
            'MINDY1' => 'FAM63A',
            'MINDY2' => 'FAM63B',
            'PIMREG' => 'FAM64A',
            'RIPOR1' => 'FAM65A',
            'RIPOR2' => 'FAM65B',
            'RIPOR3' => 'FAM65C',
            'MIGA1' => 'FAM73A',
            'FAM90A10P' => 'FAM90A10',
            'FBH1' => 'FBXO18',
            'FDX2' => 'FDX1L',
            'VEGFD' => 'FIGF',
            'FRG1BP' => 'FRG1B',
            'MRM2' => 'FTSJ2',
            'FYB1' => 'FYB',
            'GAREM1' => 'GAREM',
            'GAREM2' => 'GAREML',
            'CASTOR3' => 'GATS',
            'CASTOR1' => 'GATSL3',
            'NIPSNAP2' => 'GBAS',
            'GCN1' => 'GCN1L1',
            'CPTP' => 'GLTPD1',
            'BICRA' => 'GLTSCR1',
            'BICRAL' => 'GLTSCR1L',
            'NOP53' => 'GLTSCR2',
            'RACK1' => 'GNB2L1',
            'LINC00866' => 'GOLGA7B-DT',
            'GOLGA8IP' => 'GOLGA8I',
            'ADGRF2' => 'GPR111',
            'ADGRG4' => 'GPR112',
            'ADGRF3' => 'GPR113',
            'ADGRF5' => 'GPR116',
            'ADGRA2' => 'GPR124',
            'ADGRA3' => 'GPR125',
            'ADGRG6' => 'GPR126',
            'ADGRG7' => 'GPR128',
            'ADGRD2' => 'GPR144',
            'ADGRG2' => 'GPR64',
            'ADGRG3' => 'GPR97',
            'ADGRV1' => 'GPR98',
            'GRAMD2A' => 'GRAMD2',
            'GRAMD2B' => 'GRAMD3',
            'LINC00514' => 'GREP1',
            'HASPIN' => 'GSG2',
            'GTSE1-AS1' => 'GTSE1-DT',
            'GUCY1A1' => 'GUCY1A3',
            'GUCY1B1' => 'GUCY1B3',
            'H1FX-AS1' => 'H1-10-AS1',
            'HILS1' => 'H1-9P',
            'HIST2H2BA' => 'H2BP1',
            'H3F3AP4' => 'H3P6',
            'PUDP' => 'HDHD1',
            'DNAAF5' => 'HEATR2',
            'HJV' => 'HFE2',
            'MFSD14A' => 'HIAT1',
            'MFSD14B' => 'HIATL1',
            'JPT1' => 'HN1',
            'JPT2' => 'HN1L',
            'HNRNPU-AS1' => 'HNRNPU',
            'RIDA' => 'HRSP12',
            'IBA57-AS1' => 'IBA57-DT',
            'LINC00337' => 'ICMT-DT',
            'LMNTD1' => 'IFLTD1',
            'JCHAIN' => 'IGJ',
            'ELP1' => 'IKBKAP',
            'IL10RB-AS1' => 'IL10RB-DT',
            'PATJ' => 'INADL',
            'FAM212B-AS1' => 'INKA2-AS1',
            'INTS4P2' => 'INTS4L2',
            'MRVI1-AS1' => 'IRAG1-AS1',
            'ACOD1' => 'IRG1',
            'KDM7A' => 'JHDM1D',
            'PUM3' => 'KIAA0020',
            'DELE1' => 'KIAA0141',
            'WASHC5' => 'KIAA0196',
            'SUSD6' => 'KIAA0247',
            'ECPAS' => 'KIAA0368',
            'MARF1' => 'KIAA0430',
            'KHDC4' => 'KIAA0907',
            'TMEM131L' => 'KIAA0922',
            'ICE1' => 'KIAA0947',
            'MYORG' => 'KIAA1161',
            'NWD2' => 'KIAA1239',
            'ARFGEF3' => 'KIAA1244',
            'KIF1BP' => 'KIAA1279',
            'CCDC191' => 'KIAA1407',
            'VIRMA' => 'KIAA1429',
            'RIC1' => 'KIAA1432',
            'TRMT9B' => 'KIAA1456',
            'JCAD' => 'KIAA1462',
            'FAM234B' => 'KIAA1467',
            'CIP2A' => 'KIAA1524',
            'SHTN1' => 'KIAA1598',
            'SHISAL1' => 'KIAA1644',
            'IQCN' => 'KIAA1683',
            'CEP295' => 'KIAA1731',
            'CFAP74' => 'KIAA1751',
            'MFSD4B' => 'KIAA1919',
            'NEXMIF' => 'KIAA2022',
            'KIRREL1' => 'KIRREL',
            'AFG1L' => 'LACE1',
            'RTL6' => 'LDOC1L',
            'CNMD' => 'LECT1',
            'P3H1' => 'LEPRE1',
            'P3H2' => 'LEPREL1',
            'P3H4' => 'LEPREL4',
            'LHFPL6' => 'LHFP',
            'BRD3OS' => 'LINC00094',
            'FAM236A' => 'LINC00684',
            'CELSR3-AS1' => 'LINC02585',
            'MEOX2-AS1' => 'LINC02587',
            'BREA2' => 'LINC02878',
            'C10orf142' => 'LINC02881',
            'C8orf49' => 'LINC02905',
            'C7orf77' => 'LINC03043',
            'LINS1' => 'LINS',
            'LLPH-AS1' => 'LLPH-DT',
            'ADGRL1' => 'LPHN1',
            'LINC01771' => 'LRP8-DT',
            'CARMIL1' => 'LRRC16A',
            'CARMIL3' => 'LRRC16B',
            'LRRC3-AS1' => 'LRRC3-DT',
            'DRC3' => 'LRRC48',
            'ETFRF1' => 'LYRM5',
            'MASCRNA' => 'MALAT1',
            'MAN1B1-AS1' => 'MAN1B1-DT',
            'CGAS' => 'MB21D1',
            'BORCS8' => 'MEF2BNB',
            'BORCS8-MEF2B' => 'MEF2BNB-MEF2B',
            'BHMG1' => 'MEIOSIN',
            'MESD' => 'MESDC2',
            'EEF1AKMT2' => 'METTL10',
            'CSKMT' => 'METTL12',
            'ETFBKMT' => 'METTL20',
            'EEF1AKMT3' => 'METTL21B',
            'MELTF' => 'MFI2',
            'MFSD14C' => 'MFSD14CP',
            'MFSD4A' => 'MFSD4',
            'SLC49A3' => 'MFSD7',
            'MAFG-AS1' => 'MILIP',
            'RIOX2' => 'MINA',
            'LOC284454' => 'MIR23AHG',
            'CENPU' => 'MLF1IP',
            'MAP3K20-AS1' => 'MLK7-AS1',
            'AFDN-DT' => 'MLLT4-AS1',
            'AFDN' => 'MLLT4',
            'MRE11' => 'MRE11A',
            'MRPL57' => 'MRP63',
            'MTERF2' => 'MTERFD3',
            'TESMIN' => 'MTL5',
            'SMIM37' => 'MTLN',
            'CAVIN4' => 'MURC',
            'COPS9' => 'MYEOV2',
            'DKFZP434K028' => 'MYRF-AS1',
            'ICE2' => 'NARG2',
            'NCBP2-AS2' => 'NCBP2AS2',
            'NSMCE3' => 'NDNL2',
            'NDUFA6-AS1' => 'NDUFA6-DT',
            'C11orf72' => 'NDUFV1-DT',
            'SNU13' => 'NHP2L1',
            'NRDC' => 'NRD1',
            'LINC01693' => 'NTRAS',
            'NUP58' => 'NUPL1',
            'NUPR2' => 'NUPR1L',
            'STN1' => 'OBFC1',
            'RNF219-AS1' => 'OBI1-AS1',
            'ARMC4P1' => 'ODAD2P1',
            'OR8G2P' => 'OR8G2',
            'LOC653786' => 'OTOAP1',
            'PAK5' => 'PAK7',
            'PARD3-AS1' => 'PARD3-DT',
            'PRKN' => 'PARK2',
            'PAXIP1-AS1' => 'PAXIP1-DT',
            'PCNX1' => 'PCNX',
            'PCNX2' => 'PCNXL2',
            'PCNX4' => 'PCNXL4',
            'HRAT5' => 'PDCD6-DT',
            'GATD1' => 'PDDC1',
            'SMIM25' => 'PELATON',
            'GATB' => 'PET112',
            'PIDD1' => 'PIDD',
            'PIK3IP1-AS1' => 'PIK3IP1-DT',
            'C5orf66' => 'PITX1-AS1',
            'UBXN10-AS1' => 'PLA2G2C',
            'KIZ' => 'PLK1S1',
            'PNMA8A' => 'PNMAL1',
            'PNMA8B' => 'PNMAL2',
            'PLPP1' => 'PPAP2A',
            'PLPP3' => 'PPAP2B',
            'PLPP2' => 'PPAP2C',
            'PLPP5' => 'PPAPDC1B',
            'PLPP6' => 'PPAPDC2',
            'PLPP7' => 'PPAPDC3',
            'LINC00637' => 'PPP1R13B-DT',
            'PTPA' => 'PPP2R4',
            'CAVIN3' => 'PRKCDBP',
            'PRMT10' => 'PRMT9',
            'OPRPN' => 'PROL1',
            'PLPBP' => 'PROSC',
            'INAFM1' => 'PRR24',
            'PRSS46P' => 'PRSS46',
            'DISP3' => 'PTCHD2',
            'HACD3' => 'PTPLAD1',
            'HACD1' => 'PTPLA',
            'PTPN20' => 'PTPN20B',
            'CAVIN1' => 'PTRF',
            'NECTIN1' => 'PVRL1',
            'NECTIN2' => 'PVRL2',
            'NECTIN3' => 'PVRL3',
            'NECTIN4' => 'PVRL4',
            'PYCR3' => 'PYCRL',
            'QTRT2' => 'QTRTD1',
            'RAB29' => 'RAB7L1',
            'LINC01185' => 'REL-DT',
            'COP1' => 'RFWD2',
            'GBAT2' => 'RFX5-AS1',
            'RTL9' => 'RGAG1',
            'RTL5' => 'RGAG4',
            'CARMIL2' => 'RLTPR',
            'RNASEH1-AS1' => 'RNASEH1-DT',
            'RNF139-AS1' => 'RNF139-DT',
            'RPSAP58' => 'RPSA2',
            'CNOT9' => 'RQCD1',
            'RRS1-AS1' => 'RRS1-DT',
            'RSPH14' => 'RTDR1',
            'RTF2' => 'RTFDC1',
            'ZBED9' => 'SCAND3',
            'SCXA' => 'SCX',
            'CAVIN2' => 'SDPR',
            'SELENON' => 'SEPN1',
            'SELENOP' => 'SEPP1',
            'LINC00266-1' => 'SEPTIN14P20',
            'SEPT4-AS1' => 'SEPTIN4-AS1',
            'SEPT7-AS1' => 'SEPTIN7-DT',
            'SEPT7P2' => 'SEPTIN7P2',
            'SELENOW' => 'SEPW1',
            'SGO2' => 'SGOL2',
            'SEM1' => 'SHFM1',
            'FAM35BP' => 'SHLD2P1',
            'FAM35DP' => 'SHLD2P3',
            'MTREX' => 'SKIV2L2',
            'LINC01184' => 'SLC12A2-DT',
            'SLC22A20P' => 'SLC22A20',
            'PRELID3A' => 'SLMO1',
            'PRELID3B' => 'SLMO2',
            'PPP4R3C' => 'SMEK3P',
            'SMIM11A' => 'SMIM11',
            'LRRC75A-AS1' => 'SNHG29',
            'LINC02001' => 'SNHG30',
            'MIR3607' => 'SNORD138',
            'MTCL1' => 'SOGA2',
            'SPACA6' => 'SPACA6P',
            'SPART' => 'SPG20',
            'SPTY2D1OS' => 'SPTY2D1-AS1',
            'SQOR' => 'SQRDL',
            'SSC4D' => 'SRCRB4D',
            'PRG1' => 'SRGN',
            'SRPRA' => 'SRPR',
            'SSX8' => 'SSX8P',
            'STK4-AS1' => 'STK4-DT',
            'CENPX' => 'STRA13',
            'SUCLG2-AS1' => 'SUCLG2-DT',
            'KMT5C' => 'SUV420H2',
            'ELOC' => 'TCEB1',
            'ELOB' => 'TCEB2',
            'ELOA2' => 'TCEB3B',
            'ELOA3' => 'TCEB3C',
            'ELOA3D' => 'TCEB3CL2',
            'ELOA' => 'TCEB3',
            'TNS2' => 'TENC1',
            'LINC01529' => 'TEX14BP',
            'CATSPERZ' => 'TEX40',
            'HIPSTR' => 'TFAP2A-AS2',
            'TBXT' => 'T',
            'TM4SF19-TCTEX1D2' => 'TM4SF19-DYNLT2B',
            'TNRC6C-AS1' => 'TMC6',
            'STIMATE' => 'TMEM110',
            'TMEM14EP' => 'TMEM14E',
            'TMEM161B-AS1' => 'TMEM161B-DT',
            'MFSD13A' => 'TMEM180',
            'NEMP1' => 'TMEM194A',
            'NEMP2' => 'TMEM194B',
            'LINC01869' => 'TMEM277P',
            'CLTRN' => 'TMEM27',
            'CEMIP2' => 'TMEM2',
            'TMEM30CP' => 'TMEM30C',
            'PIP4P2' => 'TMEM55A',
            'PIP4P1' => 'TMEM55B',
            'MACO1' => 'TMEM57',
            'RXYLT1' => 'TMEM5',
            'LINC00950' => 'TMEM8B',
            'MYMK' => 'TMEM8C',
            'TOMM70' => 'TOMM70A',
            'TRIM49D2' => 'TRIM49D2P',
            'EIPR1' => 'TSSC1',
            'CFAP70' => 'TTC18',
            'CFAP46' => 'TTC40',
            'TTLL13P' => 'TTLL13',
            'UBA6-AS1' => 'UBA6-DT',
            'UBE2Q2L' => 'UBE2Q2P16',
            'UBL7-AS1' => 'UBL7-DT',
            'UBR5-AS1' => 'UBR5-DT',
            'UCHL1-AS1' => 'UCHL1-DT',
            'UFD1' => 'UFD1L',
            'UPK3BL1' => 'UPK3BL',
            'ATP5MD' => 'USMG5',
            'USP12-AS2' => 'USP12-DT',
            'USP17L1' => 'USP17L1P',
            'USP27X-AS1' => 'USP27X-DT',
            'USP46-AS1' => 'USP46-DT',
            'UTP11' => 'UTP11L',
            'LOC100506113' => 'UVRAG-DT',
            'VNN3' => 'VNN3P',
            'DCAF1' => 'VPRBP',
            'INTS14' => 'VWA9',
            'WASHC1' => 'WASH1',
            'RCC1L' => 'WBSCR16',
            'GALNT17' => 'WBSCR17',
            'BUD23' => 'WBSCR22',
            'METTL27' => 'WBSCR27',
            'TMEM270' => 'WBSCR28',
            'CFAP52' => 'WDR16',
            'CFAP44' => 'WDR52',
            'CFAP57' => 'WDR65',
            'NSD2' => 'WHSC1',
            'NSD3' => 'WHSC1L1',
            'PYM1' => 'WIBG',
            'YTHDF3-AS1' => 'YTHDF3-DT',
            'RTL4' => 'ZCCHC16',
            'RTL3' => 'ZCCHC5',
            'TMEM35B' => 'ZMYM6NB',
            'FLJ26850' => 'ZNF473CR',
            'ZNF582-AS1' => 'ZNF582-DT',
            'CBLL2' => 'ZNF645',
            'ZNF812P' => 'ZNF812',
            'ZNRD1ASP' => 'ZNRD1-AS1',
            'SSSCA1-AS1' => 'ZNRD2-DT',
            'ZRANB2-AS2' => 'ZRANB2-DT',
            'ZUP1' => 'ZUFSP',
        );
    }





    // FIXME: This function does not have a clearly matching name.
    function prepareMappings ()
    {
        // Returns an array that map VEP columns to LOVD columns.

        $aColumnMappings = array(
            'chromosome' => 'chromosome',
            'position' => 'position', // lovd_getVariantDescription() needs this.
            'QUAL' => 'VariantOnGenome/Sequencing/Quality',
            'FILTERvcf' => 'VariantOnGenome/Sequencing/Filter',
            'Consequence' => 'VariantOnTranscript/GVS/Function', // Will be translated.
            // 'GATKCaller' => 'VariantOnGenome/Sequencing/GATKcaller',
            'Feature' => 'transcriptid',
            'CDS_position' => 'VariantOnTranscript/Position',
            'HGVSc' => 'VariantOnTranscript/DNA',
            'HGVSp' => 'VariantOnTranscript/Protein',
            // 'Grantham' => 'VariantOnTranscript/Prediction/Grantham',
            // 'INDB_COUNT_UG' => 'VariantOnGenome/InhouseDB/Count/UG',
            // 'INDB_COUNT_HC' => 'VariantOnGenome/InhouseDB/Count/HC',
            // 'GLOBAL_VN' => 'VariantOnGenome/InhouseDB/Position/Global/Samples_w_coverage',
            // 'GLOBAL_VF_HET' => 'VariantOnGenome/InhouseDB/Count/Global/Heterozygotes',
            // 'GLOBAL_VF_HOM' => 'VariantOnGenome/InhouseDB/Count/Global/Homozygotes',
            // 'WITHIN_PANEL_VN' => 'VariantOnGenome/InhouseDB/Position/InPanel/Samples_w_coverage',
            // 'WITHIN_PANEL_VF_HET' => 'VariantOnGenome/InhouseDB/Count/InPanel/Heterozygotes',
            // 'WITHIN_PANEL_VF_HOM' => 'VariantOnGenome/InhouseDB/Count/InPanel/Homozygotes',
            // 'OUTSIDE_PANEL_VN' => 'VariantOnGenome/InhouseDB/Position/OutOfPanel/Samples_w_coverage',
            // 'OUTSIDE_PANEL_VF_HET' => 'VariantOnGenome/InhouseDB/Count/OutOfPanel/Heterozygotes',
            // 'OUTSIDE_PANEL_VF_HOM' => 'VariantOnGenome/InhouseDB/Count/OutOfPanel/Homozygotes',
            'AF1000G' => 'VariantOnGenome/Frequency/1000G',
            'rsID' => 'VariantOnGenome/dbSNP',
            // 'AFESP5400' => 'VariantOnGenome/Frequency/EVS', // Will be divided by 100 later.
            // 'CALC_GONL_AF' => 'VariantOnGenome/Frequency/GoNL',
            // 'AFGONL' => 'VariantOnGenome/Frequency/GoNL_old',
            // 'EXAC_AF' => 'VariantOnGenome/Frequency/ExAC',
            // 'MutationTaster_pred' => 'VariantOnTranscript/Prediction/MutationTaster',
            // 'MutationTaster_score' => 'VariantOnTranscript/Prediction/MutationTaster/Score',
            // 'Polyphen2_HDIV_score' => 'VariantOnTranscript/PolyPhen/HDIV',
            // 'Polyphen2_HVAR_score' => 'VariantOnTranscript/PolyPhen/HVAR',
            // 'SIFT_score' => 'VariantOnTranscript/Prediction/SIFT',
            'CADD_raw' => 'VariantOnGenome/CADD/Raw',
            'CADD_phred' => 'VariantOnGenome/CADD/Phred',
            'HGMD_association' => 'VariantOnGenome/HGMD/Association',
            'HGMD_reference' => 'VariantOnGenome/HGMD/Reference',
            'phyloP' => 'VariantOnGenome/Conservation_score/PhyloP',
            'scorePhastCons' => 'VariantOnGenome/Conservation_score/Phast',
            'GT' => 'allele',
            'GQ' => 'VariantOnGenome/Sequencing/GenoType/Quality',
            'DP' => 'VariantOnGenome/Sequencing/Depth/Total',
            'DPREF' => 'VariantOnGenome/Sequencing/Depth/Ref',
            'DPALT' => 'VariantOnGenome/Sequencing/Depth/Alt',
            'ALTPERC' => 'VariantOnGenome/Sequencing/Depth/Alt/Fraction',
            // 'GT_Father' => 'VariantOnGenome/Sequencing/Father/GenoType',
            // 'GQ_Father' => 'VariantOnGenome/Sequencing/Father/GenoType/Quality',
            // 'DP_Father' => 'VariantOnGenome/Sequencing/Father/Depth/Total',
            // 'ALTPERC_Father' => 'VariantOnGenome/Sequencing/Father/Depth/Alt/Fraction',
            // 'ISPRESENT_Father' => 'VariantOnGenome/Sequencing/Father/VarPresent',
            // 'GT_Mother' => 'VariantOnGenome/Sequencing/Mother/GenoType',
            // 'GQ_Mother' => 'VariantOnGenome/Sequencing/Mother/GenoType/Quality',
            // 'DP_Mother' => 'VariantOnGenome/Sequencing/Mother/Depth/Total',
            // 'ALTPERC_Mother' => 'VariantOnGenome/Sequencing/Mother/Depth/Alt/Fraction',
            // 'ISPRESENT_Mother' => 'VariantOnGenome/Sequencing/Mother/VarPresent',

            // Mappings for fields used to process other fields but not imported into the database.
            'SYMBOL' => 'symbol',
            'HGNC_ID' => 'id_hgnc',
            'REF' => 'ref',
            'ALT' => 'alt',
            'Existing_variation' => 'existing_variation'
        );

        return $aColumnMappings;
    }
}
